name: minecraft_flutter_launche
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  sidebarx: ^0.17.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  file_picker: ^8.1.6
  permission_handler: ^10.4.0
  crypto: ^3.0.3
  dio: ^5.2.1
  archive: ^3.4.0
  encrypt: ^5.0.1
  json_annotation: ^4.8.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/background.jpg
